#!/usr/bin/env ruby
require "./Expense.rb"
require "./Report.rb"
#
# Main program
# check that two arguments are given
if ARGV.count < 2
  puts "usage: ./Report myBankimport.csv \"Business Checking\""
	exit
end
report = Report.new()
report.importFromBankCSV(ARGV[0], ARGV[1])
puts report.lines

